// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContactEditor: typeof import('./src/components/cv/ContactEditor.vue')['default']
    ContentClear: typeof import('./src/components/controls/ContentClear.vue')['default']
    ContentDownload: typeof import('./src/components/controls/ContentDownload.vue')['default']
    ContentImport: typeof import('./src/components/controls/ContentImport.vue')['default']
    ContentManager: typeof import('./src/components/controls/ContentManager.vue')['default']
    ContentPrint: typeof import('./src/components/controls/ContentPrint.vue')['default']
    CvAside: typeof import('./src/components/cv/CvAside.vue')['default']
    CvAsideList: typeof import('./src/components/cv/CvAsideList.vue')['default']
    CvContact: typeof import('./src/components/cv/CvContact.vue')['default']
    CvContent: typeof import('./src/components/cv/CvContent.vue')['default']
    CvSection: typeof import('./src/components/cv/CvSection.vue')['default']
    CvSectionPart: typeof import('./src/components/cv/CvSectionPart.vue')['default']
    IconCarbonAdd: typeof import('~icons/carbon/add')['default']
    IconCarbonCheckmark: typeof import('~icons/carbon/checkmark')['default']
    IconCarbonChevronDown: typeof import('~icons/carbon/chevron-down')['default']
    IconCarbonClose: typeof import('~icons/carbon/close')['default']
    IconCarbonCopy: typeof import('~icons/carbon/copy')['default']
    IconCarbonDocument: typeof import('~icons/carbon/document')['default']
    IconCarbonDocumentImport: typeof import('~icons/carbon/document-import')['default']
    IconCarbonDraggable: typeof import('~icons/carbon/draggable')['default']
    IconCarbonDragVertical: typeof import('~icons/carbon/drag-vertical')['default']
    IconCarbonEdit: typeof import('~icons/carbon/edit')['default']
    IconCarbonMenu: typeof import('~icons/carbon/menu')['default']
    IconCarbonPageBreak: typeof import('~icons/carbon/page-break')['default']
    IconCarbonPrinter: typeof import('~icons/carbon/printer')['default']
    IconCarbonReset: typeof import('~icons/carbon/reset')['default']
    IconCarbonSave: typeof import('~icons/carbon/save')['default']
    IconCarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    IconCarbonWarningAlt: typeof import('~icons/carbon/warning-alt')['default']
    InlineControls: typeof import('./src/components/controls/InlineControls.vue')['default']
    Modal: typeof import('./src/components/dialog/Modal.vue')['default']
    MouseOver: typeof import('./src/components/util/MouseOver.vue')['default']
    PartEditor: typeof import('./src/components/cv/PartEditor.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    SectionEditor: typeof import('./src/components/cv/SectionEditor.vue')['default']
    SettingsManager: typeof import('./src/components/controls/SettingsManager.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarManager: typeof import('./src/components/controls/SidebarManager.vue')['default']
    SkillEditor: typeof import('./src/components/cv/SkillEditor.vue')['default']
    ToggleButton: typeof import('./src/components/util/ToggleButton.vue')['default']
    ToggleSidebar: typeof import('./src/components/controls/ToggleSidebar.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
